import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="gpx_strava",
    version="0.2",
    author="Safwen Bouali",
    author_email="safwen.bouali@outlook.com",
    description="A package that simplifies usefull operations on gpx data generated by strava.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/SafwenBouali/gpx_strava",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)